spring:
  datasource:
    url: jdbc:h2:file:~/chantdefleur;IFEXISTS=true
    driverClassName: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port: 8181

